"""empty message

Revision ID: fcd5bfb9ba80
Revises: db24b48497b4
Create Date: 2021-05-12 20:18:40.525853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd5bfb9ba80'
down_revision = 'db24b48497b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'level')
    # ### end Alembic commands ###
