# Generated by Django 3.2.3 on 2021-05-29 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_de_criacao', models.DateTimeField(auto_now=True)),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_credito', to='contas.conta')),
                ('conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_debito', to='contas.conta')),
            ],
            options={
                'db_table': 'tb_transacoes',
            },
        ),
    ]
