"""empty message

Revision ID: 0591ae8b4145
Revises: 3a8d148f3641
Create Date: 2021-06-14 21:07:10.809252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0591ae8b4145'
down_revision = '3a8d148f3641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debit_account_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('credit_account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_credit_account_id', 'tb_accounts', ['credit_account_id'], ['id'])
        batch_op.create_foreign_key('fk_debit_account_id', 'tb_accounts', ['debit_account_id'], ['id'])
        batch_op.drop_column('debit_account')
        batch_op.drop_column('credit_account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_account', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('debit_account', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_accounts', ['debit_account'], ['id'])
        batch_op.create_foreign_key(None, 'tb_accounts', ['credit_account'], ['id'])
        batch_op.drop_column('credit_account_id')
        batch_op.drop_column('debit_account_id')

    # ### end Alembic commands ###
