"""empty message

Revision ID: 0cdd4c1e709d
Revises: b015990b01ba
Create Date: 2021-06-11 21:04:12.097832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdd4c1e709d'
down_revision = 'b015990b01ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
