"""empty message

Revision ID: 193a4903ab87
Revises: 851b8a032953
Create Date: 2021-06-14 20:34:41.692788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193a4903ab87'
down_revision = '851b8a032953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transactions', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###
