"""empty message

Revision ID: 30422bdfed40
Revises: 93e385fa6e69
Create Date: 2021-06-11 22:22:29.329340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30422bdfed40'
down_revision = '93e385fa6e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_accounts', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
