"""empty message

Revision ID: 851b8a032953
Revises: 30422bdfed40
Create Date: 2021-06-14 19:14:37.205958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851b8a032953'
down_revision = '30422bdfed40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit_account', sa.Integer(), nullable=False),
    sa.Column('credit_account', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['credit_account'], ['tb_accounts.id'], ),
    sa.ForeignKeyConstraint(['debit_account'], ['tb_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_transactions')
    # ### end Alembic commands ###
